### ISSUE TITLE
write requirements.txt

### ISSUE THREAD

**Issue by bmewing** [bmewing/mgsub-python#4]

**Comment by Dyex719** [comment]
In mgsub.py

`import re`
`from operator import itemgetter`

Both the libraries you require for your program require just the python standard library. So as of now, your requirements.txt can be left empty.
If you require any other libraries you can simply list them into the requirement.txt (one in each line), followed by the version number (optional).

Then the user can simply do `pip install -r requirements.txt`

**Comment by bmewing** [comment]
Is it best practices to have a requirements.txt that's empty or no file at all?

**Comment by kofrezo** [comment]
Shall we close this issue then?
